### ISSUE TITLE
Please switch the static dependency on MomentJS to a ranged peer dependency, so that we as consumers can decide which version of MomentJS to use

### ISSUE THREAD

**Issue by elliotleelewis** [rezendeneto/moment-with-locales-es6#1]
I.E. switch where it says in the `package.json`:

```
"dependencies": {
  "moment": "2.18.1"
}
```

to

```
"peerDependencies": {
  "moment": "^2.0.0"
}
```

This will allow us to use newer versions of MomentJS, without you having to worry about creating new releases for this package every time a newer version of MomentJS is released.

**Comment by rezendeneto** [comment]
Hi @elliotleelewis, thanks for the input.

I've just published a new version: v1.0.1, please update it in your projects.
